name: Runner
on:
  push:
jobs:
  ubuntu:
    name: ubuntu
    runs-on: depot-ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: mxschmitt/action-tmate@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@more-verbose
      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Testing PHP version
        run: |
          php -v