name: Runner workflow
on:
  push:
jobs:
  runner:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [blacksmith-2vcpu-ubuntu-2204, ubuntu-22.04, blacksmith-2vcpu-ubuntu-2404, ubuntu-24.04, depot-ubuntu-22.04]
        php-version:
          - 8.7

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php-version }}
          extensions: http
        env:
          verbose: v
          runner: github
          use_package_cache: true
      - run: |
          php -v
          php -m
      
  
