name: Runner workflow
on:
  push:
jobs:
  runner:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [blacksmith-2vcpu-ubuntu-2404, blacksmith-2vcpu-ubuntu-2404-arm, ubuntu-24.04, ubuntu-24.04-arm, depot-ubuntu-24.04, depot-ubuntu-24.04-arm]
        php-version:
          - 5.6
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
          - 8.4
          - 8.5
          - 8.6
          - 8.7

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php-version }}
        env:
          use_builds_cache: true
      - name: Testing PHP version
        env:
          EXPECTED_PHP_VERSION: ${{ matrix.php-version }}
        run: |
          php -r '$expected = getenv("EXPECTED_PHP_VERSION"); if(strpos(phpversion(), $expected) === false) {throw new Exception("Wrong PHP version Installed");}'
          php -v
          php -m
      
  
